### PR TITLE
Add badges, fix spello, and test unresolvable dials

### PR DESCRIPTION
**Pull request by anacrolix**
I've picked out the parts of https://github.com/libp2p/go-reuseport/pull/67 that I'm happy with. @Stebalien is the best course of action to remove that go file if it breaks gx? @Petroav I'd prefer any tests of Dial and Listen use the existing style with testify, and port zero to allow parallel tests, and `-count > 1` without weird behaviour.

### CODE REVIEW

**Comment by petroav** [comment]
@anacrolix thank you for the follow up!

Is `testify` a library I should be using when writing tests in for `libp2p` packages?

> `-count > 1` without weird behaviour

Not sure what this means, can you clarify?

The `Listen()` and `Dial()` methods as written in `testDialFromListeningPort` do not exercise the code in the `go-reuseport` package but are instead called on a locally created `ListenConfig`. Why not call the wrapper methods in `interface.go`?

Can explain why you think `ResolveAddr()` should not be explicitly tested? The next repo I planned to contribute tests to is `go-sockaddr` which contains a number of methods similar to `ResolveAddr()`. I was planning on testing those methods in a similar way.

**Comment by Stebalien** [comment]
> Is testify a library I should be using when writing tests in for libp2p packages?

It's a library that @anacrolix chose to use here. We don't use it anywhere else (that I know of) and haven't discussed switching over to it.

@anacrolix would you like to file an issue in go-libp2p proposing that we make it our go-to testing framework? I believer @marten-seemann prefers ginkgo/gomega.

**Comment by anacrolix** [comment]
@petroav Your tests used explicit ports on localhost. They may be flaky when tests are executed in parallel, or multiple times. The `Listen` and `Dial` methods are at this point only there for backward compatibility (consumers should be using `Control` directly from Go 1.11 onwards). If they're worth testing to increase arbitrary code coverage metrics, it should be done by passing in the listen and dial functions to `testDialFromListeningPort` which correctly avoids port collisions per above and avoids repeating the error handling all over the place.

I'm not sure `ResolveAddr` even belongs in this package. I've opened #69 for it. Perhaps you'll have more insight after looking at `go-sockaddr`?

@Stebalien I don't want to standardize on testing suites unless someone has an issue with something. There's too much bike-shedding, and personal preference should be allowed.

**Comment by anacrolix** [comment]
This PR should be merged. Further additions are open to further discussion, but there's no reason not to merge this at this point.

**Comment by Stebalien** [comment]
> I don't want to standardize on testing suites unless someone has an issue with something. There's too much bike-shedding, and personal preference should be allowed.

You were asking @petroav to use it so I figured you might want to propose that it be used everywhere. I hind sight, I guess you just meant "use it here" because that's what all the other tests are doing (makes sense).

**Pull request merged**
