### PR TITLE
Update Travis CI to use standard test script.  Add basic Makefile.

### PR DESCRIPTION
**Pull request by kevina**

### CODE REVIEW

**Comment by kevina** [comment]
`go vet` is failing:
```
singlepoll/ctx.go:11: the backgroundcancel function is not used on all paths (possible context leak)

singlepoll/ctx.go:12: this return statement may be reached without using the backgroundcancel var defined on line 11
```
similar to problem in https://github.com/libp2p/go-libp2p/pull/245

Maybe we should use codeclimate like @Kubuxu suggested on irc instead of just running go-vet.

**Comment by Stebalien** [comment]
Fixed in #33.

**Comment by kevina** [comment]
Rebased on top of #33 and got a weird test failure:https://travis-ci.org/libp2p/go-reuseport/jobs/303763318

**Comment by Stebalien** [comment]
@kevina should be fixed by https://github.com/ipfs/ci-helpers/pull/3

**Pull request merged**
