### PR TITLE
feat: add support for ListenUDP

### PR DESCRIPTION
**Pull request by sruehl**
This PR adds support for the ListenUDP function of the net package

### CODE REVIEW

**Comment by sruehl** [comment]
multicast and broadcast http://www.kohala.com/start/mcast.api.txt

**Comment by sruehl** [comment]
ok nvm that PR is non-sense, sorry for the inconvenience

**Comment by sruehl** [comment]
for those who find this by google: you can cast the packetCon to a udpCon:
```
packetConn, err := reuseport.ListenPacket("udp","192.168.178.255:47808")
udpConn := packetConn.(*net.UDPConn)
```

**Comment by sot-tech** [comment]
Hello.

> Can you tell us about your use case?

UDP server, which reached limit of using event loop (`for { ... sock.ReadFrom(*bytea) ... }`) for incoming datagrams.

> How does this work? If I'm listening on the same local address twice, how does the kernel know which listener to deliver the packets to?

Connection for certain protocol (i.e. UDP) identified by tuple of 4 values: **src** address, **src** port, dst address, dst port, so if you're listening same endpoint twice with REUSE*, but there are two peers with different src addresses and/or ports, kernel will (well... [should](https://bugzilla.kernel.org/show_bug.cgi?id=200755)) route them to diferrent listeners.

Just FYI, @sruehl's workaround with assertion works fine.

**Pull request closed without merging**
