### PR TITLE
switch to golang.org/x/sys

### LINKED ISSUE #22: Support Linux on ARM64
The standard Go syscall package doesn't/won't implement EpollWait on ARM64:

```
EpollWait returned error: function not implemented. Continuing. linux.go:189
```

The fix should be simple: replace the `syscall` import with `golang.org/x/sys/unix`

### PR DESCRIPTION
**Pull request by Stebalien**
depends on jbenet/go-sockaddr#5

fixes #22

### CODE REVIEW

**Comment by Kubuxu** [comment]
Could you add the OSX to travis config? I would do it myself but you PRed from the fork.

**Comment by Stebalien** [comment]
Hm. I'm getting failures on Travis. Is Travis not allowing reuseport?

**Comment by Kubuxu** [comment]
@Stebalien no idea, but tests pass for me locally with increased fdlimit.

**Comment by Kubuxu** [comment]
@Stebalien no idea, but tests pass for me locally with increased fdlimit.

**Comment by Stebalien** [comment]
Yeah. It's Travis :(.

**Comment by whyrusleeping** [comment]
passes on OSX for me, fails on linux though due to too many file descriptors. (same failure on master)

**Pull request merged**
